language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements_dev.txt"
# command to run tests
script:
  - pep8 --verbose --show-pep8 ccuapi
  - pylint ccuapi
  - nosetests -v ccuapi

env: AKAMAI_USERNAME=my_user AKAMAI_PASSWORD=my_password